name: iverilog compile on PR

on: [push, pull_request]
jobs:
  iverilog-compile:
    runs-on: ubuntu-latest
    steps:
      - name: SetUp SSH
        env:
          SSH_PRIVATE: ${{ secrets.ACTIONS_SSH_PRIVATE }}
          SSH_PUBLIC: ${{ secrets.ACTIONS_SSH_PUBLIC }}
          ARTIFACT_NAME: "RTL_build_$(TZ='America/New_York' date '+%F-%H')"
          OUT_PATH: ${{ env.PWD }}/out
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.SSH_PRIVATE }}" > ~/.ssh/id_rsa
          echo "${{ env.SSH_PUBLIC }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
      - name: Download required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog
          git clone --recurse-submodules git@github.com:Clarkson-RISC-V-2023/IP_ROM.git
          tree
      - name: Clone project repo and compile with iverilog
        run: |
          mkdir -p out
          iverilog -o out/rom.vpp -s tb_rom rom/verif/tb_rom.sv rom/rtl/rom.sv rom/rtl/init_rom.mem
          tree
