name: ROM tb compile with iverilog on PR push

on: 
  push: 
    branches: 
      - main 
  pull_request:
  
jobs:
  iverilog-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Download required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog
      - name : Checkout repo
        uses: actions/checkout@v3
        with:
          path: rom
      - name: Compile with iverilog
        run: |
          cd rom
          mkdir -p out
          iverilog -s tb_rom -o out/rom_sim -g2005-sv -D ROM_INIT_PATH=\"./init_rom.mem\" verif/tb_rom.sv rtl/rom.sv
          cd out/
          vvp rom_sim
          cd ..
          tree
          echo Build COMPLETE
      - name: Upload Artifact 
        uses: actions/upload-artifact@v2
        with:
          name: "RTL_build"
          path: |
            **/out/**
          if-no-files-found: error
